/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family: SeedIcon
///      fonts:
///       - asset: fonts/seed-icon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';
  
class SeedIcons {
  SeedIcons._();

  static const _fontFam = 'SeedIcon';
  static const String? _fontPkg = null;
  
  static const IconData icon_add_circle_fill =
       IconData(0xea01, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_add_circle_regular =
       IconData(0xea02, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_add_circle_thin =
       IconData(0xea03, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_add_fill =
       IconData(0xea04, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_add_regular =
       IconData(0xea05, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_add_thin =
       IconData(0xea06, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_aeb_fill =
       IconData(0xea07, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_aeb_regular =
       IconData(0xea08, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_aeb_thin =
       IconData(0xea09, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_android_share_fill =
       IconData(0xea0a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_android_share_regular =
       IconData(0xea0b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_android_share_thin =
       IconData(0xea0c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_downward_fill =
       IconData(0xea0d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_downward_regular =
       IconData(0xea0e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_downward_thin =
       IconData(0xea0f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_down_fill =
       IconData(0xea10, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_down_regular =
       IconData(0xea11, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_down_thin =
       IconData(0xea12, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_up_fill =
       IconData(0xea13, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_up_regular =
       IconData(0xea14, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_drop_up_thin =
       IconData(0xea15, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_fill =
       IconData(0xea16, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_regular =
       IconData(0xea17, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_thin =
       IconData(0xea18, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_upward_fill =
       IconData(0xea19, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_upward_regular =
       IconData(0xea1a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_arrow_upward_thin =
       IconData(0xea1b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_article_fill =
       IconData(0xea1c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_article_regular =
       IconData(0xea1d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_article_thin =
       IconData(0xea1e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_backward_fill =
       IconData(0xea1f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_backward_regular =
       IconData(0xea20, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_backward_thin =
       IconData(0xea21, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bill_fill =
       IconData(0xea22, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bill_regular =
       IconData(0xea23, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bill_thin =
       IconData(0xea24, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bold_fill =
       IconData(0xea25, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bold_regular =
       IconData(0xea26, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bold_thin =
       IconData(0xea27, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_fill =
       IconData(0xea28, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_list_fill =
       IconData(0xea29, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_list_regular =
       IconData(0xea2a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_list_thin =
       IconData(0xea2b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_regular =
       IconData(0xea2c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_bookmark_thin =
       IconData(0xea2d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_calendar_fill =
       IconData(0xea2e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_calendar_regular =
       IconData(0xea2f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_calendar_thin =
       IconData(0xea30, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_declined_fill =
       IconData(0xea31, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_declined_regular =
       IconData(0xea32, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_declined_thin =
       IconData(0xea33, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_fill =
       IconData(0xea34, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_regular =
       IconData(0xea35, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_call_thin =
       IconData(0xea36, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_camera_fill =
       IconData(0xea37, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_camera_regular =
       IconData(0xea38, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_camera_thin =
       IconData(0xea39, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_around_view_fill =
       IconData(0xea3a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_around_view_regular =
       IconData(0xea3b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_around_view_thin =
       IconData(0xea3c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_blind_spot_fill =
       IconData(0xea3d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_blind_spot_regular =
       IconData(0xea3e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_blind_spot_thin =
       IconData(0xea3f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_cruise_control_fill =
       IconData(0xea40, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_cruise_control_regular =
       IconData(0xea41, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_cruise_control_thin =
       IconData(0xea42, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_epb_fill =
       IconData(0xea43, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_epb_regular =
       IconData(0xea44, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_epb_thin =
       IconData(0xea45, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_fill =
       IconData(0xea46, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_seat_fill =
       IconData(0xea47, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_seat_regular =
       IconData(0xea48, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_seat_thin =
       IconData(0xea49, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_steering_wheel_fill =
       IconData(0xea4a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_steering_wheel_regular =
       IconData(0xea4b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_heated_steering_wheel_thin =
       IconData(0xea4c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ldws_fill =
       IconData(0xea4d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ldws_regular =
       IconData(0xea4e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ldws_thin =
       IconData(0xea4f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_leather_seat_fill =
       IconData(0xea50, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_leather_seat_regular =
       IconData(0xea51, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_leather_seat_thin =
       IconData(0xea52, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_navigation_fill =
       IconData(0xea53, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_navigation_regular =
       IconData(0xea54, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_navigation_thin =
       IconData(0xea55, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_power_trunk_fill =
       IconData(0xea56, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_power_trunk_regular =
       IconData(0xea57, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_power_trunk_thin =
       IconData(0xea58, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_camera_fill =
       IconData(0xea59, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_camera_regular =
       IconData(0xea5a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_camera_thin =
       IconData(0xea5b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_sensor_fill =
       IconData(0xea5c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_sensor_regular =
       IconData(0xea5d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_rear_sensor_thin =
       IconData(0xea5e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_regular =
       IconData(0xea5f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_smart_key_fill =
       IconData(0xea60, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_smart_key_regular =
       IconData(0xea61, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_smart_key_thin =
       IconData(0xea62, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_thin =
       IconData(0xea63, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ventilation_seat_fill =
       IconData(0xea64, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ventilation_seat_regular =
       IconData(0xea65, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_car_ventilation_seat_thin =
       IconData(0xea66, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cart_fill =
       IconData(0xea67, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cart_regular =
       IconData(0xea68, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cart_thin =
       IconData(0xea69, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_certification_fill =
       IconData(0xea6a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_certification_regular =
       IconData(0xea6b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_certification_thin =
       IconData(0xea6c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_challenge_fill =
       IconData(0xea6d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_challenge_regular =
       IconData(0xea6e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_challenge_thin =
       IconData(0xea6f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chart_fill =
       IconData(0xea70, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chart_regular =
       IconData(0xea71, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chart_thin =
       IconData(0xea72, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chat_bubble_check_fill =
       IconData(0xea73, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chat_bubble_check_regular =
       IconData(0xea74, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chat_bubble_check_thin =
       IconData(0xea75, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_fill =
       IconData(0xea76, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_regular =
       IconData(0xea77, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_send_fill =
       IconData(0xea78, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_send_regular =
       IconData(0xea79, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_send_thin =
       IconData(0xea7a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chatting_thin =
       IconData(0xea7b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_fill =
       IconData(0xea7c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_flower_fill =
       IconData(0xea7d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_flower_regular =
       IconData(0xea7e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_flower_thin =
       IconData(0xea7f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_regular =
       IconData(0xea80, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_check_thin =
       IconData(0xea81, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_left_fill =
       IconData(0xea82, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_left_regular =
       IconData(0xea83, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_left_thin =
       IconData(0xea84, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_right_fill =
       IconData(0xea85, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_right_regular =
       IconData(0xea86, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_chevron_right_thin =
       IconData(0xea87, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_click_fill =
       IconData(0xea88, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_click_regular =
       IconData(0xea89, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_click_thin =
       IconData(0xea8a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_clock_fill =
       IconData(0xea8b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_clock_regular =
       IconData(0xea8c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_clock_thin =
       IconData(0xea8d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_close_fill =
       IconData(0xea8e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_close_regular =
       IconData(0xea8f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_close_thin =
       IconData(0xea90, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cobuying_fill =
       IconData(0xea91, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cobuying_regular =
       IconData(0xea92, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_cobuying_thin =
       IconData(0xea93, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_community_fill =
       IconData(0xea94, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_community_regular =
       IconData(0xea95, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_community_thin =
       IconData(0xea96, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_condo_fill =
       IconData(0xea97, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_condo_regular =
       IconData(0xea98, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_condo_thin =
       IconData(0xea99, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_fill =
       IconData(0xea9a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_pay_fill =
       IconData(0xea9b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_pay_regular =
       IconData(0xea9c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_pay_thin =
       IconData(0xea9d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_profile_fill =
       IconData(0xea9e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_profile_regular =
       IconData(0xea9f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_profile_thin =
       IconData(0xeaa0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_regular =
       IconData(0xeaa1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_confirmation_thin =
       IconData(0xeaa2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_contents_fill =
       IconData(0xeaa3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_contents_regular =
       IconData(0xeaa4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_contents_thin =
       IconData(0xeaa5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_convert_fill =
       IconData(0xeaa6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_convert_regular =
       IconData(0xeaa7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_convert_thin =
       IconData(0xeaa8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_copy_fill =
       IconData(0xeaa9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_copy_regular =
       IconData(0xeaaa, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_copy_thin =
       IconData(0xeaab, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_download_done_fill =
       IconData(0xeaac, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_download_done_regular =
       IconData(0xeaad, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_download_done_thin =
       IconData(0xeaae, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_fill =
       IconData(0xeaaf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_regular =
       IconData(0xeab0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_thin =
       IconData(0xeab1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_used_fill =
       IconData(0xeab2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_used_regular =
       IconData(0xeab3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_coupon_used_thin =
       IconData(0xeab4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delete_keyboard_fill =
       IconData(0xeab5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delete_keyboard_regular =
       IconData(0xeab6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delete_keyboard_thin =
       IconData(0xeab7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delivery_fill =
       IconData(0xeab8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delivery_regular =
       IconData(0xeab9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_delivery_thin =
       IconData(0xeaba, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_download_fill =
       IconData(0xeabb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_download_regular =
       IconData(0xeabc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_download_thin =
       IconData(0xeabd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_edit_fill =
       IconData(0xeabe, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_edit_regular =
       IconData(0xeabf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_edit_thin =
       IconData(0xeac0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_bad_fill =
       IconData(0xeac1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_bad_regular =
       IconData(0xeac2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_bad_thin =
       IconData(0xeac3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_fill =
       IconData(0xeac4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_regular =
       IconData(0xeac5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_emoticon_thin =
       IconData(0xeac6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_fill =
       IconData(0xeac7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_less_fill =
       IconData(0xeac8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_less_regular =
       IconData(0xeac9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_less_thin =
       IconData(0xeaca, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_more_fill =
       IconData(0xeacb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_more_regular =
       IconData(0xeacc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_more_thin =
       IconData(0xeacd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_regular =
       IconData(0xeace, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_expand_thin =
       IconData(0xeacf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_file_fill =
       IconData(0xead0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_file_regular =
       IconData(0xead1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_file_thin =
       IconData(0xead2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_filter02_fill =
       IconData(0xead3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_filter02_regular =
       IconData(0xead4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_filter02_thin =
       IconData(0xead5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_forward_fill =
       IconData(0xead6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_forward_regular =
       IconData(0xead7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_forward_thin =
       IconData(0xead8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gender_fill =
       IconData(0xead9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gender_regular =
       IconData(0xeada, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gender_thin =
       IconData(0xeadb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_global_fill =
       IconData(0xeadc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_global_regular =
       IconData(0xeadd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_global_thin =
       IconData(0xeade, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable2_fill =
       IconData(0xeadf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable2_regular =
       IconData(0xeae0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable2_thin =
       IconData(0xeae1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable_fill =
       IconData(0xeae2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable_regular =
       IconData(0xeae3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_enable_thin =
       IconData(0xeae4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_fill =
       IconData(0xeae5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_regular =
       IconData(0xeae6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_gps_thin =
       IconData(0xeae7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_groupchat_king_fill =
       IconData(0xeae8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_groupchat_king_regular =
       IconData(0xeae9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_groupchat_king_thin =
       IconData(0xeaea, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_handle_fill =
       IconData(0xeaeb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_handle_regular =
       IconData(0xeaec, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_handle_thin =
       IconData(0xeaed, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_hashtag_fill =
       IconData(0xeaee, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_hashtag_regular =
       IconData(0xeaef, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_hashtag_thin =
       IconData(0xeaf0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_headphone_fill =
       IconData(0xeaf1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_headphone_regular =
       IconData(0xeaf2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_headphone_thin =
       IconData(0xeaf3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_heart_fill =
       IconData(0xeaf4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_heart_regular =
       IconData(0xeaf5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_heart_thin =
       IconData(0xeaf6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_help_fill =
       IconData(0xeaf7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_help_regular =
       IconData(0xeaf8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_help_thin =
       IconData(0xeaf9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helpcenter_fill =
       IconData(0xeafa, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helpcenter_regular =
       IconData(0xeafb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helpcenter_thin =
       IconData(0xeafc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helper_fill =
       IconData(0xeafd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helper_regular =
       IconData(0xeafe, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_helper_thin =
       IconData(0xeaff, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_home_fill =
       IconData(0xeb00, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_home_regular =
       IconData(0xeb01, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_home_thin =
       IconData(0xeb02, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_house_fill =
       IconData(0xeb03, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_house_regular =
       IconData(0xeb04, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_house_thin =
       IconData(0xeb05, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_housekeeping_book_fill =
       IconData(0xeb06, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_housekeeping_book_regular =
       IconData(0xeb07, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_housekeeping_book_thin =
       IconData(0xeb08, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_import_fill =
       IconData(0xeb09, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_import_regular =
       IconData(0xeb0a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_import_thin =
       IconData(0xeb0b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_info_fill =
       IconData(0xeb0c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_info_regular =
       IconData(0xeb0d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_info_thin =
       IconData(0xeb0e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_fill =
       IconData(0xeb0f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_list_fill =
       IconData(0xeb10, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_list_regular =
       IconData(0xeb11, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_list_thin =
       IconData(0xeb12, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_regular =
       IconData(0xeb13, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_interest_thin =
       IconData(0xeb14, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_invite_fill =
       IconData(0xeb15, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_invite_regular =
       IconData(0xeb16, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_invite_thin =
       IconData(0xeb17, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_ios_share_fill =
       IconData(0xeb18, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_ios_share_regular =
       IconData(0xeb19, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_ios_share_thin =
       IconData(0xeb1a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_jobs_fill =
       IconData(0xeb1b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_jobs_regular =
       IconData(0xeb1c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_jobs_thin =
       IconData(0xeb1d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyboard_hiding_fill =
       IconData(0xeb1e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyboard_hiding_regular =
       IconData(0xeb1f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyboard_hiding_thin =
       IconData(0xeb20, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyword_fill =
       IconData(0xeb21, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyword_regular =
       IconData(0xeb22, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_keyword_thin =
       IconData(0xeb23, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_laptop_fill =
       IconData(0xeb24, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_laptop_regular =
       IconData(0xeb25, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_laptop_thin =
       IconData(0xeb26, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_leaf_fill =
       IconData(0xeb27, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_leaf_regular =
       IconData(0xeb28, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_leaf_thin =
       IconData(0xeb29, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_card_fill =
       IconData(0xeb2a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_card_regular =
       IconData(0xeb2b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_card_thin =
       IconData(0xeb2c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_check_fill =
       IconData(0xeb2d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_check_regular =
       IconData(0xeb2e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_check_thin =
       IconData(0xeb2f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_fill =
       IconData(0xeb30, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_regular =
       IconData(0xeb31, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_select_fill =
       IconData(0xeb32, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_select_regular =
       IconData(0xeb33, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_select_thin =
       IconData(0xeb34, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_thin =
       IconData(0xeb35, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_thumbnail_fill =
       IconData(0xeb36, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_thumbnail_regular =
       IconData(0xeb37, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_list_thumbnail_thin =
       IconData(0xeb38, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_location_fill =
       IconData(0xeb39, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_location_regular =
       IconData(0xeb3a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_location_thin =
       IconData(0xeb3b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_lock_fill =
       IconData(0xeb3c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_lock_regular =
       IconData(0xeb3d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_lock_thin =
       IconData(0xeb3e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_loudspeaker_fill =
       IconData(0xeb3f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_loudspeaker_regular =
       IconData(0xeb40, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_loudspeaker_thin =
       IconData(0xeb41, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_map_fill =
       IconData(0xeb42, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_map_regular =
       IconData(0xeb43, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_map_thin =
       IconData(0xeb44, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_check_fill =
       IconData(0xeb45, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_check_regular =
       IconData(0xeb46, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_check_thin =
       IconData(0xeb47, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_fill =
       IconData(0xeb48, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_regular =
       IconData(0xeb49, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_market_thin =
       IconData(0xeb4a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mention_fill =
       IconData(0xeb4b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mention_regular =
       IconData(0xeb4c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mention_thin =
       IconData(0xeb4d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_menu_fill =
       IconData(0xeb4e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_menu_regular =
       IconData(0xeb4f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_menu_thin =
       IconData(0xeb50, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_fill =
       IconData(0xeb51, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_off_fill =
       IconData(0xeb52, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_off_regular =
       IconData(0xeb53, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_off_thin =
       IconData(0xeb54, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_regular =
       IconData(0xeb55, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mic_thin =
       IconData(0xeb56, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mission_fill =
       IconData(0xeb57, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mission_regular =
       IconData(0xeb58, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mission_thin =
       IconData(0xeb59, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mobile_fill =
       IconData(0xeb5a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mobile_regular =
       IconData(0xeb5b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_mobile_thin =
       IconData(0xeb5c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_send_fill =
       IconData(0xeb5d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_send_regular =
       IconData(0xeb5e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_send_thin =
       IconData(0xeb5f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_won_fill =
       IconData(0xeb60, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_won_regular =
       IconData(0xeb61, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_money_won_thin =
       IconData(0xeb62, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_moon_fill =
       IconData(0xeb63, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_moon_regular =
       IconData(0xeb64, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_moon_thin =
       IconData(0xeb65, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_horiz_fill =
       IconData(0xeb66, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_horiz_regular =
       IconData(0xeb67, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_horiz_thin =
       IconData(0xeb68, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_vert_fill =
       IconData(0xeb69, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_vert_regular =
       IconData(0xeb6a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_more_vert_thin =
       IconData(0xeb6b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_fill =
       IconData(0xeb6c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_profile_fill =
       IconData(0xeb6d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_profile_regular =
       IconData(0xeb6e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_profile_thin =
       IconData(0xeb6f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_regular =
       IconData(0xeb70, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_my_thin =
       IconData(0xeb71, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_near_me_fill =
       IconData(0xeb72, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_near_me_regular =
       IconData(0xeb73, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_near_me_thin =
       IconData(0xeb74, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_newtopic_fill =
       IconData(0xeb75, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_newtopic_regular =
       IconData(0xeb76, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_newtopic_thin =
       IconData(0xeb77, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_note_fill =
       IconData(0xeb78, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_note_regular =
       IconData(0xeb79, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_note_thin =
       IconData(0xeb7a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_fall_fill =
       IconData(0xeb7b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_fall_regular =
       IconData(0xeb7c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_fall_thin =
       IconData(0xeb7d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_fill =
       IconData(0xeb7e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_off_fill =
       IconData(0xeb7f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_off_regular =
       IconData(0xeb80, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_off_thin =
       IconData(0xeb81, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_regular =
       IconData(0xeb82, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_notification_thin =
       IconData(0xeb83, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_order_fill =
       IconData(0xeb84, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_order_regular =
       IconData(0xeb85, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_order_thin =
       IconData(0xeb86, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pause_fill =
       IconData(0xeb87, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pause_regular =
       IconData(0xeb88, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pause_thin =
       IconData(0xeb89, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_payment_fill =
       IconData(0xeb8a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_payment_regular =
       IconData(0xeb8b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_payment_thin =
       IconData(0xeb8c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_percent_fill =
       IconData(0xeb8d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_percent_regular =
       IconData(0xeb8e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_percent_thin =
       IconData(0xeb8f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_crop_fill =
       IconData(0xeb90, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_crop_regular =
       IconData(0xeb91, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_crop_thin =
       IconData(0xeb92, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_draw_fill =
       IconData(0xeb93, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_draw_regular =
       IconData(0xeb94, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_draw_thin =
       IconData(0xeb95, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_fill =
       IconData(0xeb96, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_regular =
       IconData(0xeb97, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_rotate_fill =
       IconData(0xeb98, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_rotate_regular =
       IconData(0xeb99, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_rotate_thin =
       IconData(0xeb9a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_edit_thin =
       IconData(0xeb9b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_fill =
       IconData(0xeb9c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_regular =
       IconData(0xeb9d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_several_fill =
       IconData(0xeb9e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_several_regular =
       IconData(0xeb9f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_several_thin =
       IconData(0xeba0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_photo_thin =
       IconData(0xeba1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_play_fill =
       IconData(0xeba2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_play_regular =
       IconData(0xeba3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_play_thin =
       IconData(0xeba4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_poll_fill =
       IconData(0xeba5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_poll_regular =
       IconData(0xeba6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_poll_thin =
       IconData(0xeba7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_price_won_fill =
       IconData(0xeba8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_price_won_regular =
       IconData(0xeba9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_price_won_thin =
       IconData(0xebaa, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_product_fill =
       IconData(0xebab, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_product_regular =
       IconData(0xebac, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_product_thin =
       IconData(0xebad, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_badge_fill =
       IconData(0xebae, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_badge_regular =
       IconData(0xebaf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_badge_thin =
       IconData(0xebb0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_fill =
       IconData(0xebb1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_regular =
       IconData(0xebb2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_profile_thin =
       IconData(0xebb3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_prohibition_fill =
       IconData(0xebb4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_prohibition_regular =
       IconData(0xebb5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_prohibition_thin =
       IconData(0xebb6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pushpin_fill =
       IconData(0xebb7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pushpin_regular =
       IconData(0xebb8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_pushpin_thin =
       IconData(0xebb9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_question_check_fill =
       IconData(0xebba, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_question_check_regular =
       IconData(0xebbb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_question_check_thin =
       IconData(0xebbc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_redo_fill =
       IconData(0xebbd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_redo_regular =
       IconData(0xebbe, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_redo_thin =
       IconData(0xebbf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_refund_fill =
       IconData(0xebc0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_refund_regular =
       IconData(0xebc1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_refund_thin =
       IconData(0xebc2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_remove_circle_fill =
       IconData(0xebc3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_remove_circle_regular =
       IconData(0xebc4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_remove_circle_thin =
       IconData(0xebc5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_fill =
       IconData(0xebc6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_mission_fill =
       IconData(0xebc7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_mission_regular =
       IconData(0xebc8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_mission_thin =
       IconData(0xebc9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_re_fill =
       IconData(0xebca, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_re_regular =
       IconData(0xebcb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_re_thin =
       IconData(0xebcc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_regular =
       IconData(0xebcd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reply_thin =
       IconData(0xebce, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_report_fill =
       IconData(0xebcf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_report_regular =
       IconData(0xebd0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_report_thin =
       IconData(0xebd1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reservation_fill =
       IconData(0xebd2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reservation_regular =
       IconData(0xebd3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_reservation_thin =
       IconData(0xebd4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_restaurant_fill =
       IconData(0xebd5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_restaurant_regular =
       IconData(0xebd6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_restaurant_thin =
       IconData(0xebd7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_retry_fill =
       IconData(0xebd8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_retry_regular =
       IconData(0xebd9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_retry_thin =
       IconData(0xebda, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_review_star_fill =
       IconData(0xebdb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_review_star_regular =
       IconData(0xebdc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_review_star_thin =
       IconData(0xebdd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_scanner_fill =
       IconData(0xebde, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_scanner_regular =
       IconData(0xebdf, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_scanner_thin =
       IconData(0xebe0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_doc_fill =
       IconData(0xebe1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_doc_regular =
       IconData(0xebe2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_doc_thin =
       IconData(0xebe3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_fill =
       IconData(0xebe4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_regular =
       IconData(0xebe5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_search_thin =
       IconData(0xebe6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sell_fill =
       IconData(0xebe7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sell_regular =
       IconData(0xebe8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sell_thin =
       IconData(0xebe9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_setting_fill =
       IconData(0xebea, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_setting_regular =
       IconData(0xebeb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_setting_thin =
       IconData(0xebec, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_signout_fill =
       IconData(0xebed, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_signout_regular =
       IconData(0xebee, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_signout_thin =
       IconData(0xebef, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sort_fill =
       IconData(0xebf0, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sort_regular =
       IconData(0xebf1, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sort_thin =
       IconData(0xebf2, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_article_fill =
       IconData(0xebf3, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_article_regular =
       IconData(0xebf4, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_article_thin =
       IconData(0xebf5, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_fill =
       IconData(0xebf6, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_regular =
       IconData(0xebf7, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_story_thin =
       IconData(0xebf8, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtract_circle_fill =
       IconData(0xebf9, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtract_circle_regular =
       IconData(0xebfa, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtract_circle_thin =
       IconData(0xebfb, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtraction_fill =
       IconData(0xebfc, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtraction_regular =
       IconData(0xebfd, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_subtraction_thin =
       IconData(0xebfe, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_suggest_fill =
       IconData(0xebff, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_suggest_regular =
       IconData(0xec00, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_suggest_thin =
       IconData(0xec01, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sun_fill =
       IconData(0xec02, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sun_regular =
       IconData(0xec03, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_sun_thin =
       IconData(0xec04, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingdown_fill =
       IconData(0xec05, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingdown_regular =
       IconData(0xec06, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingdown_thin =
       IconData(0xec07, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingup_fill =
       IconData(0xec08, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingup_regular =
       IconData(0xec09, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_talkingup_thin =
       IconData(0xec0a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_text_fill =
       IconData(0xec0b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_text_regular =
       IconData(0xec0c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_text_thin =
       IconData(0xec0d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_down_fill =
       IconData(0xec0e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_down_regular =
       IconData(0xec0f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_down_thin =
       IconData(0xec10, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_up_fill =
       IconData(0xec11, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_up_regular =
       IconData(0xec12, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_thumb_up_thin =
       IconData(0xec13, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_toolbox_fill =
       IconData(0xec14, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_toolbox_regular =
       IconData(0xec15, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_toolbox_thin =
       IconData(0xec16, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_translate_fill =
       IconData(0xec17, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_translate_regular =
       IconData(0xec18, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_translate_thin =
       IconData(0xec19, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_trash_fill =
       IconData(0xec1a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_trash_regular =
       IconData(0xec1b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_trash_thin =
       IconData(0xec1c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_undo_fill =
       IconData(0xec1d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_undo_regular =
       IconData(0xec1e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_undo_thin =
       IconData(0xec1f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_user_group_fill =
       IconData(0xec20, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_user_group_regular =
       IconData(0xec21, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_user_group_thin =
       IconData(0xec22, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_video_fill =
       IconData(0xec23, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_video_regular =
       IconData(0xec24, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_video_thin =
       IconData(0xec25, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_fill =
       IconData(0xec26, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_off_fill =
       IconData(0xec27, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_off_regular =
       IconData(0xec28, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_off_thin =
       IconData(0xec29, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_regular =
       IconData(0xec2a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_view_count_thin =
       IconData(0xec2b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_off_fill =
       IconData(0xec2c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_off_regular =
       IconData(0xec2d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_off_thin =
       IconData(0xec2e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_on_fill =
       IconData(0xec2f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_on_regular =
       IconData(0xec30, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_volume_on_thin =
       IconData(0xec31, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_vote_fill =
       IconData(0xec32, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_vote_regular =
       IconData(0xec33, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_vote_thin =
       IconData(0xec34, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_voucher_fill =
       IconData(0xec35, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_voucher_regular =
       IconData(0xec36, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_voucher_thin =
       IconData(0xec37, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_walk_fill =
       IconData(0xec38, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_walk_regular =
       IconData(0xec39, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_walk_thin =
       IconData(0xec3a, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_warning_fill =
       IconData(0xec3b, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_warning_regular =
       IconData(0xec3c, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_warning_thin =
       IconData(0xec3d, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_fill =
       IconData(0xec3e, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_frequent_use_fill =
       IconData(0xec3f, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_frequent_use_regular =
       IconData(0xec40, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_frequent_use_thin =
       IconData(0xec41, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_regular =
       IconData(0xec42, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_story_fill =
       IconData(0xec43, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_story_regular =
       IconData(0xec44, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_story_thin =
       IconData(0xec45, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData icon_write_thin =
       IconData(0xec46, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData rabbit =
       IconData(0xec47, fontFamily: _fontFam, fontPackage: _fontPkg);
  static const IconData turtle =
       IconData(0xec48, fontFamily: _fontFam, fontPackage: _fontPkg);
}
